export const OrganisationsDummyData = [
    {
        id:1,
        orgLogo: '../logos/logo1.png',
        orgTitle:"IT Technologies",
        orgDomain:"IT Service",
        orgEmail:"info@ittechnologies.com",
        orgStatus: true,
    },
    {
        id:2,
        orgLogo:"../logos/logo2.png",
        orgTitle:"FIN 101",
        orgDomain:"Finance Service",
        orgEmail:"info@f101.com",
        orgStatus: false,
    },
    {
        id:3,
        orgLogo:"../logos/logo3.png",
        orgTitle:"Hotel Planner.com",
        orgDomain:"Online Booking",
        orgEmail:"info@hp.com",
        orgStatus: false,
    },
    {
        id:4,
        orgLogo:"../logos/logo4.png",
        orgTitle:"Shopify",
        orgDomain:"Ecommerce",
        orgEmail:"info@shopify.com",
        orgStatus: false,
    },
    {
        id:5,
        orgLogo:"../logos/logo5.png",
        orgTitle:"Food House",
        orgDomain:"Hospitality",
        orgEmail:"info@foodhouse.com",
        orgStatus: false,
    },
    {
        id:6,
        orgLogo:"../logos/logo6.png",
        orgTitle:"Health Equity",
        orgDomain:"Healthcare",
        orgEmail:"info@healthequity.com",
        orgStatus: true,
    },
    {
        id:7,
        orgLogo:"../logos/logo7.png",
        orgTitle:"Commercial Journal",
        orgDomain:"Construction Service",
        orgEmail:"info@commercialj.com",
        orgStatus: true,
    },
    {
        id:8,
        orgLogo:"../logos/logo8.png",
        orgTitle:"Auto Zone",
        orgDomain:"Automobiles",
        orgEmail:"info@autozone.com",
        orgStatus: false,
    },
    {
        id:9,
        orgLogo:"../logos/logo9.png",
        orgTitle:"MacKiev",
        orgDomain:"IT Service",
        orgEmail:"info@mackiev.com",
        orgStatus: true,
    },
    {
        id:10,
        orgLogo:"../logos/logo5.png",
        orgTitle:"IT Technologies",
        orgDomain:"IT Service",
        orgEmail:"info@ittechnologies.com",
        orgStatus: true,
    },
    {
        id:11,
        orgLogo:"../logos/logo3.png",
        orgTitle:"FIN 101",
        orgDomain:"Finance Service",
        orgEmail:"info@f101.com",
        orgStatus: false,
    },
    {
        id:12,
        orgLogo:"../logos/logo1.png",
        orgTitle:"Hotel Planner.com",
        orgDomain:"Online Booking",
        orgEmail:"info@hp.com",
        orgStatus: true,
    },
    {
        id:13,
        orgLogo:"../logos/logo9.png",
        orgTitle:"IT Technologies",
        orgDomain:"IT Service",
        orgEmail:"info@ittechnologies.com",
        orgStatus:  true,
    },
    {
        id:14,
        orgLogo:"../logos/logo3.png",
        orgTitle:"FIN 101",
        orgDomain:"Finance Service",
        orgEmail:"info@f101.com",
        orgStatus: true,
    },
    {
        id:15,
        orgLogo:"../logos/logo7.png",
        orgTitle:"Hotel Planner.com",
        orgDomain:"Online Booking",
        orgEmail:"info@hp.com",
        orgStatus: false,
    },
    {
        id:16,
        orgLogo:"../logos/logo2.png",
        orgTitle:"Hotel Planner.com",
        orgDomain:"Online Booking",
        orgEmail:"info@hp.com",
        orgStatus: true,
    },
    {
        id:17,
        orgLogo:"../logos/logo8.png",
        orgTitle:"Hotel Planner.com",
        orgDomain:"Online Booking",
        orgEmail:"info@hp.com",
        orgStatus: false,
    },
]